import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import archiver from 'archiver';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3001;
const DB_PATH = path.join(__dirname, 'db.json');
const TEMP_BASE_DIR = path.join(__dirname, 'temp');

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Ensure temp base directory exists
if (!fs.existsSync(TEMP_BASE_DIR)) {
  fs.mkdirSync(TEMP_BASE_DIR, { recursive: true });
}

// Helper to read DB
const readDB = () => {
  try {
    if (!fs.existsSync(DB_PATH)) {
      fs.writeFileSync(DB_PATH, JSON.stringify([]));
    }
    const data = fs.readFileSync(DB_PATH, 'utf8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Error reading DB:', err);
    return [];
  }
};

// Helper to write DB
const writeDB = (data) => {
  try {
    fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2));
  } catch (err) {
    console.error('Error writing DB:', err);
  }
};

// Helper to write to local temp directory and validate Chrome V3 Manifest schema
const writeToTempAndValidate = (project, versionObj) => {
  const tempDir = path.join(TEMP_BASE_DIR, project.id, `v${versionObj.version}`);
  
  // Clean & Ensure directory exists
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
  fs.mkdirSync(tempDir, { recursive: true });

  // Write all files physically to disk
  versionObj.files.forEach(f => {
    const filePath = path.join(tempDir, f.name);
    // Ensure any nested directory generated by the LLM exists
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, f.content, 'utf8');
  });

  // Validate manifest.json
  const manifestFile = versionObj.files.find(f => f.name.toLowerCase() === 'manifest.json');
  if (!manifestFile) {
    throw new Error('Validation Error: manifest.json is missing from the extension folder.');
  }

  try {
    const manifestJson = JSON.parse(manifestFile.content);
    if (parseInt(manifestJson.manifest_version) !== 3) {
      throw new Error('Validation Error: The manifest.json must use manifest_version 3 to be a valid modern extension.');
    }
    if (!manifestJson.name) {
      throw new Error('Validation Error: manifest.json is missing the mandatory "name" property.');
    }
    if (!manifestJson.version) {
      throw new Error('Validation Error: manifest.json is missing the mandatory "version" property.');
    }

    // Helper to check if file exists in list
    const fileExists = (name) => {
      if (!name) return true;
      const cleanName = name.replace(/^\.?\//, '');
      return versionObj.files.some(f => {
        const fClean = f.name.replace(/^\.?\//, '');
        return fClean.toLowerCase() === cleanName.toLowerCase();
      });
    };

    // 1. Check content scripts js/css references
    if (manifestJson.content_scripts && Array.isArray(manifestJson.content_scripts)) {
      manifestJson.content_scripts.forEach((cs, index) => {
        if (cs.js && Array.isArray(cs.js)) {
          cs.js.forEach(jsFile => {
            if (!fileExists(jsFile)) {
              throw new Error(`Validation Error: "content_scripts[${index}]" references missing JavaScript file "${jsFile}".`);
            }
          });
        }
        if (cs.css && Array.isArray(cs.css)) {
          cs.css.forEach(cssFile => {
            if (!fileExists(cssFile)) {
              throw new Error(`Validation Error: "content_scripts[${index}]" references missing CSS file "${cssFile}".`);
            }
          });
        }
      });
    }

    // 2. Check background service worker / script references
    if (manifestJson.background) {
      if (manifestJson.background.service_worker) {
        const swFile = manifestJson.background.service_worker;
        if (!fileExists(swFile)) {
          throw new Error(`Validation Error: "background.service_worker" references missing file "${swFile}".`);
        }
      }
      if (manifestJson.background.scripts && Array.isArray(manifestJson.background.scripts)) {
        manifestJson.background.scripts.forEach(scriptFile => {
          if (!fileExists(scriptFile)) {
            throw new Error(`Validation Error: "background.scripts" references missing file "${scriptFile}".`);
          }
        });
      }
    }

    // 3. Check action default popup
    if (manifestJson.action && manifestJson.action.default_popup) {
      const popupFile = manifestJson.action.default_popup;
      if (!fileExists(popupFile)) {
        throw new Error(`Validation Error: "action.default_popup" references missing file "${popupFile}".`);
      }
    }

    // 4. Check options pages references
    if (manifestJson.options_page && !fileExists(manifestJson.options_page)) {
      throw new Error(`Validation Error: "options_page" references missing file "${manifestJson.options_page}".`);
    }
    if (manifestJson.options_ui && manifestJson.options_ui.page) {
      const optUiPage = manifestJson.options_ui.page;
      if (!fileExists(optUiPage)) {
        throw new Error(`Validation Error: "options_ui.page" references missing file "${optUiPage}".`);
      }
    }

    // 5. Check chrome_url_overrides references
    if (manifestJson.chrome_url_overrides) {
      const overrides = manifestJson.chrome_url_overrides;
      if (overrides.newtab && !fileExists(overrides.newtab)) {
        throw new Error(`Validation Error: "chrome_url_overrides.newtab" references missing file "${overrides.newtab}".`);
      }
      if (overrides.bookmarks && !fileExists(overrides.bookmarks)) {
        throw new Error(`Validation Error: "chrome_url_overrides.bookmarks" references missing file "${overrides.bookmarks}".`);
      }
      if (overrides.history && !fileExists(overrides.history)) {
        throw new Error(`Validation Error: "chrome_url_overrides.history" references missing file "${overrides.history}".`);
      }
    }
  } catch (err) {
    if (err.message.includes('JSON')) {
      throw new Error(`Validation Error: manifest.json has syntax errors and is not valid JSON. Detail: ${err.message}`);
    }
    throw err;
  }

  return tempDir;
};

// Ultimate System Instruction to compile Chrome Extensions
const SYSTEM_INSTRUCTION = `You are a world-class AI Chrome Extension Developer expert. 
Your goal is to build fully functioning Chrome Extensions using Manifest V3 in response to the user's requirements.

You must design and output ALL necessary files (e.g. manifest.json, background.js, content.js, popup.html, popup.css, popup.js, options.html, options.js, or image placeholders if needed) to make the extension completely operational.

CRITICAL RULES:
1. You MUST use Manifest V3.
2. Provide clean, secure, and modern CSS and JavaScript code. No placeholders or "TODO" comments.
3. Every file referenced in manifest.json (e.g. in "content_scripts", "background", "action.default_popup") must be present in the files list you generate.
4. If a script or file is not needed, do not list it. Only output functional files.
5. All UI/Popups should be modern, clean, dark-themed, and responsive.

OUTPUT FORMAT:
You MUST output ONLY a valid JSON object matching the following structure. Do NOT wrap the JSON in markdown code blocks (like \`\`\`json). Do NOT add any preamble, conversational text, or explanation. Start directly with '{' and end with '}'.

{
  "name": "Professional, catchy name of the extension",
  "description": "Engaging description explaining what the extension does",
  "files": [
    {
      "name": "manifest.json",
      "content": "{ ... }"
    },
    {
      "name": "content.js",
      "content": "// JavaScript code..."
    },
    {
      "name": "popup.html",
      "content": "<!-- HTML code -->"
    }
  ]
}`;

// Helper to clean LLM response
const cleanJSONResponse = (raw) => {
  let cleaned = raw.trim();
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(json)?/, '');
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.replace(/```$/, '');
  }
  return cleaned.trim();
};

// Endpoint to list projects
app.get('/api/projects', (req, res) => {
  const db = readDB();
  res.json(db);
});

// Endpoint to generate/iterate extension
app.post('/api/generate', async (req, res) => {
  const { prompt, projectId, parentVersion, apiKey: frontendApiKey } = req.body;
  const apiKey = frontendApiKey || process.env.GEMINI_API_KEY;

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }
  if (!apiKey) {
    return res.status(400).json({ 
      error: 'Gemini API Key is missing. Please configure it in your Settings panel or set GEMINI_API_KEY in the server environment.' 
    });
  }

  const db = readDB();
  let project = null;
  let targetVersion = 1;
  let systemContext = SYSTEM_INSTRUCTION;
  let promptContent = `User requirement: "${prompt}"`;

  // Iteration logic
  if (projectId) {
    project = db.find(p => p.id === projectId);
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }
    const parentVerNum = parseInt(parentVersion) || project.versions.length;
    const parentVer = project.versions.find(v => v.version === parentVerNum);
    
    if (parentVer) {
      targetVersion = project.versions.length + 1;
      
      systemContext += `\n\nThis is an iteration. You are modifying an existing Chrome extension. Below are the files in the current version (Version ${parentVerNum}):`;
      
      parentVer.files.forEach(f => {
        systemContext += `\n\n--- File Name: ${f.name} ---\n${f.content}`;
      });

      promptContent = `The user wants to iterate on the extension. 
Existing Prompt History: ${project.promptHistory ? project.promptHistory.join(' -> ') : ''}
New requirement to apply: "${prompt}"

Modify the existing files or create new ones to achieve this request. Provide the FULL revised project files matching the original JSON format, updating the 'manifest.json' version number if necessary. Maintain existing features unless the user's new request explicitly overrides them.`;
    }
  }

  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
    
    const requestBody = {
      contents: [{
        parts: [{ text: promptContent }]
      }],
      systemInstruction: {
        parts: [{ text: systemContext }]
      },
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "OBJECT",
          properties: {
            name: { type: "STRING" },
            description: { type: "STRING" },
            files: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  name: { type: "STRING" },
                  content: { type: "STRING" }
                },
                required: ["name", "content"]
              }
            }
          },
          required: ["name", "description", "files"]
        }
      }
    };

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API returned error ${response.status}: ${errorText}`);
    }

    const result = await response.json();
    const rawText = result.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!rawText) {
      throw new Error('Gemini API returned an empty response.');
    }

    const cleanedText = cleanJSONResponse(rawText);
    const extensionData = JSON.parse(cleanedText);

    if (!extensionData.files || !Array.isArray(extensionData.files)) {
      throw new Error('LLM output does not contain files array.');
    }

    // Verify manifest.json exists
    const hasManifest = extensionData.files.some(f => f.name.toLowerCase() === 'manifest.json');
    if (!hasManifest) {
      throw new Error('LLM did not generate a manifest.json file.');
    }

    // Create project / version structure
    const newVersion = {
      version: targetVersion,
      prompt: prompt,
      createdAt: new Date().toISOString(),
      files: extensionData.files
    };

    // Temporarily write and validate on physical disk before saving to DB
    const validatedProjectObj = project || { id: crypto.randomUUID() };
    writeToTempAndValidate(validatedProjectObj, newVersion);

    if (project) {
      project.versions.push(newVersion);
      project.promptHistory = project.promptHistory || [];
      project.promptHistory.push(prompt);
      project.name = extensionData.name || project.name;
      project.description = extensionData.description || project.description;
      project.updatedAt = new Date().toISOString();
    } else {
      project = {
        id: validatedProjectObj.id,
        name: extensionData.name || 'Unnamed Extension',
        description: extensionData.description || 'Custom generated Chrome extension.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        promptHistory: [prompt],
        versions: [newVersion]
      };
      db.push(project);
    }

    writeDB(db);
    res.json(project);

  } catch (err) {
    console.error('Generation Error:', err);
    res.status(500).json({ error: err.message || 'Failed to generate extension.' });
  }
});

// Endpoint to save manual user code modifications to db
app.post('/api/projects/:projectId/versions/:version/files', (req, res) => {
  const { projectId, version } = req.params;
  const { name, content } = req.body;

  if (!name || content === undefined) {
    return res.status(400).json({ error: 'File name and content are required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  const file = ver.files.find(f => f.name === name);
  if (!file) {
    ver.files.push({ name, content });
  } else {
    file.content = content;
  }

  try {
    // Re-verify local integrity
    writeToTempAndValidate(project, ver);
    project.updatedAt = new Date().toISOString();
    writeDB(db);
    res.json(project);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to download zip compiled physically on-the-fly from temp directory
app.get('/api/download/:projectId/:version', (req, res) => {
  const { projectId, version } = req.params;
  const db = readDB();
  const project = db.find(p => p.id === projectId);
  
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  try {
    // 1. Physically write files to temp folder and validate structure
    const tempDir = writeToTempAndValidate(project, ver);

    // 2. Set up ZIP streaming
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${project.name.replace(/[^a-zA-Z0-9]/g, '_')}_v${version}.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });
    
    archive.on('error', (err) => {
      console.error('Archive error:', err);
      res.status(500).send({ error: err.message });
    });

    archive.pipe(res);

    // 3. Zip files from the physical temp directory
    archive.directory(tempDir, false);
    archive.finalize();

  } catch (err) {
    console.error('Download Error:', err);
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to delete a project and clean up its files
app.delete('/api/projects/:projectId', (req, res) => {
  const { projectId } = req.params;
  const db = readDB();
  const projectIndex = db.findIndex(p => p.id === projectId);
  if (projectIndex === -1) {
    return res.status(404).json({ error: 'Project not found' });
  }
  
  // Remove from db
  db.splice(projectIndex, 1);
  writeDB(db);

  // Remove physical files
  const projectTempDir = path.join(TEMP_BASE_DIR, projectId);
  if (fs.existsSync(projectTempDir)) {
    try {
      fs.rmSync(projectTempDir, { recursive: true, force: true });
    } catch (err) {
      console.error('Error deleting temp directory:', err);
    }
  }
  
  res.json({ success: true });
});

// Endpoint to delete a file from a project version
app.post('/api/projects/:projectId/versions/:version/files/delete', (req, res) => {
  const { projectId, version } = req.params;
  const { name } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'File name is required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  const fileIndex = ver.files.findIndex(f => f.name === name);
  if (fileIndex === -1) {
    return res.status(404).json({ error: 'File not found' });
  }

  if (name.toLowerCase() === 'manifest.json') {
    return res.status(400).json({ error: 'Cannot delete manifest.json' });
  }

  ver.files.splice(fileIndex, 1);

  try {
    writeToTempAndValidate(project, ver);
    project.updatedAt = new Date().toISOString();
    writeDB(db);
    res.json(project);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to update project metadata (rename / update description)
app.post('/api/projects/:projectId/metadata', (req, res) => {
  const { projectId } = req.params;
  const { name, description } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'Project name is required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  project.name = name;
  if (description !== undefined) {
    project.description = description;
  }
  project.updatedAt = new Date().toISOString();

  writeDB(db);
  res.json(project);
});

// Start backend
app.listen(PORT, () => {
  console.log(`Backend server is running on http://localhost:${PORT}`);
});
