import express from 'express';
import dotenv from 'dotenv';
dotenv.config();
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import archiver from 'archiver';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3001;
const DB_PATH = path.join(__dirname, 'db.json');
const TEMP_BASE_DIR = path.join(__dirname, 'temp');

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Ensure temp base directory exists
if (!fs.existsSync(TEMP_BASE_DIR)) {
  fs.mkdirSync(TEMP_BASE_DIR, { recursive: true });
}

// Helper to read DB
const readDB = () => {
  try {
    if (!fs.existsSync(DB_PATH)) {
      fs.writeFileSync(DB_PATH, JSON.stringify([]));
    }
    const data = fs.readFileSync(DB_PATH, 'utf8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Error reading DB:', err);
    return [];
  }
};

// Helper to write DB
const writeDB = (data) => {
  try {
    fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2));
  } catch (err) {
    console.error('Error writing DB:', err);
  }
};

// Helper to write to local temp directory and validate Chrome V3 Manifest schema
const writeToTempAndValidate = (project, versionObj) => {
  const tempDir = path.join(TEMP_BASE_DIR, project.id, `v${versionObj.version}`);
  
  // Clean & Ensure directory exists
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
  fs.mkdirSync(tempDir, { recursive: true });

  // Write all files physically to disk
  versionObj.files.forEach(f => {
    const filePath = path.join(tempDir, f.name);
    // Ensure any nested directory generated by the LLM exists
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, f.content, 'utf8');
  });

  // Validate manifest.json
  const manifestFile = versionObj.files.find(f => f.name.toLowerCase() === 'manifest.json');
  if (!manifestFile) {
    throw new Error('Validation Error: manifest.json is missing from the extension folder.');
  }

  try {
    const manifestJson = JSON.parse(manifestFile.content);
    if (parseInt(manifestJson.manifest_version) !== 3) {
      throw new Error('Validation Error: The manifest.json must use manifest_version 3 to be a valid modern extension.');
    }
    if (!manifestJson.name) {
      throw new Error('Validation Error: manifest.json is missing the mandatory "name" property.');
    }
    if (!manifestJson.version) {
      throw new Error('Validation Error: manifest.json is missing the mandatory "version" property.');
    }

    // Helper to check if file exists in list
    const fileExists = (name) => {
      if (!name) return true;
      const cleanName = name.replace(/^\.?\//, '');
      return versionObj.files.some(f => {
        const fClean = f.name.replace(/^\.?\//, '');
        return fClean.toLowerCase() === cleanName.toLowerCase();
      });
    };

    // 1. Check content scripts js/css references
    if (manifestJson.content_scripts && Array.isArray(manifestJson.content_scripts)) {
      manifestJson.content_scripts.forEach((cs, index) => {
        if (cs.js && Array.isArray(cs.js)) {
          cs.js.forEach(jsFile => {
            if (!fileExists(jsFile)) {
              throw new Error(`Validation Error: "content_scripts[${index}]" references missing JavaScript file "${jsFile}".`);
            }
          });
        }
        if (cs.css && Array.isArray(cs.css)) {
          cs.css.forEach(cssFile => {
            if (!fileExists(cssFile)) {
              throw new Error(`Validation Error: "content_scripts[${index}]" references missing CSS file "${cssFile}".`);
            }
          });
        }
      });
    }

    // 2. Check background service worker / script references
    if (manifestJson.background) {
      if (manifestJson.background.service_worker) {
        const swFile = manifestJson.background.service_worker;
        if (!fileExists(swFile)) {
          throw new Error(`Validation Error: "background.service_worker" references missing file "${swFile}".`);
        }
      }
      if (manifestJson.background.scripts && Array.isArray(manifestJson.background.scripts)) {
        manifestJson.background.scripts.forEach(scriptFile => {
          if (!fileExists(scriptFile)) {
            throw new Error(`Validation Error: "background.scripts" references missing file "${scriptFile}".`);
          }
        });
      }
    }

    // 3. Check action default popup
    if (manifestJson.action && manifestJson.action.default_popup) {
      const popupFile = manifestJson.action.default_popup;
      if (!fileExists(popupFile)) {
        throw new Error(`Validation Error: "action.default_popup" references missing file "${popupFile}".`);
      }
    }

    // 4. Check options pages references
    if (manifestJson.options_page && !fileExists(manifestJson.options_page)) {
      throw new Error(`Validation Error: "options_page" references missing file "${manifestJson.options_page}".`);
    }
    if (manifestJson.options_ui && manifestJson.options_ui.page) {
      const optUiPage = manifestJson.options_ui.page;
      if (!fileExists(optUiPage)) {
        throw new Error(`Validation Error: "options_ui.page" references missing file "${optUiPage}".`);
      }
    }

    // 5. Check chrome_url_overrides references
    if (manifestJson.chrome_url_overrides) {
      const overrides = manifestJson.chrome_url_overrides;
      if (overrides.newtab && !fileExists(overrides.newtab)) {
        throw new Error(`Validation Error: "chrome_url_overrides.newtab" references missing file "${overrides.newtab}".`);
      }
      if (overrides.bookmarks && !fileExists(overrides.bookmarks)) {
        throw new Error(`Validation Error: "chrome_url_overrides.bookmarks" references missing file "${overrides.bookmarks}".`);
      }
      if (overrides.history && !fileExists(overrides.history)) {
        throw new Error(`Validation Error: "chrome_url_overrides.history" references missing file "${overrides.history}".`);
      }
    }
  } catch (err) {
    if (err.message.includes('JSON')) {
      throw new Error(`Validation Error: manifest.json has syntax errors and is not valid JSON. Detail: ${err.message}`);
    }
    throw err;
  }

  return tempDir;
};

// Ultimate System Instruction to compile Chrome Extensions
const SYSTEM_INSTRUCTION = `You are a world-class AI Chrome Extension Developer expert. 
Your goal is to build fully functioning Chrome Extensions using Manifest V3 in response to the user's requirements.

You must design and output ALL necessary files (e.g. manifest.json, background.js, content.js, popup.html, popup.css, popup.js, options.html, options.js, or image placeholders if needed) to make the extension completely operational.

CRITICAL RULES:
1. You MUST use Manifest V3.
2. Provide clean, secure, and modern CSS and JavaScript code. No placeholders or "TODO" comments.
3. Every file referenced in manifest.json (e.g. in "content_scripts", "background", "action.default_popup") must be present in the files list you generate.
4. If a script or file is not needed, do not list it. Only output functional files.
5. All UI/Popups should be modern, clean, dark-themed, and responsive.

OUTPUT FORMAT:
You MUST output ONLY a valid JSON object matching the following structure. Do NOT wrap the JSON in markdown code blocks (like \`\`\`json). Do NOT add any preamble, conversational text, or explanation. Start directly with '{' and end with '}'.

{
  "name": "Professional, catchy name of the extension",
  "description": "Engaging description explaining what the extension does",
  "files": [
    {
      "name": "manifest.json",
      "content": "{ ... }"
    },
    {
      "name": "content.js",
      "content": "// JavaScript code..."
    },
    {
      "name": "popup.html",
      "content": "<!-- HTML code -->"
    }
  ]
}`;

// Helper to clean LLM response
const cleanJSONResponse = (raw) => {
  let cleaned = raw.trim();
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(json)?/, '');
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.replace(/```$/, '');
  }
  return cleaned.trim();
};

// Endpoint to list projects
app.get('/api/projects', (req, res) => {
  const db = readDB();
  res.json(db);
});

// Endpoint to generate/iterate extension
app.post('/api/generate', async (req, res) => {
  const { prompt, projectId, parentVersion, apiKey: frontendApiKey, aiProvider: frontendAiProvider } = req.body;
  const apiKey = frontendApiKey || process.env.OPENAI_API_KEY;
  const aiProvider = frontendAiProvider || 'openai';

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }
  if (!apiKey) {
    return res.status(400).json({ 
      error: 'OpenAI API Key is missing. Please configure it in your Settings panel or set OPENAI_API_KEY in the server environment.' 
    });
  }

  const db = readDB();
  let project = null;
  let targetVersion = 1;
  let systemContext = SYSTEM_INSTRUCTION;
  let promptContent = `User requirement: "${prompt}"`;

  // Iteration logic
  if (projectId) {
    project = db.find(p => p.id === projectId);
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }
    const parentVerNum = parseInt(parentVersion) || project.versions.length;
    const parentVer = project.versions.find(v => v.version === parentVerNum);
    
    if (parentVer) {
      targetVersion = project.versions.length + 1;
      
      systemContext += `\n\nThis is an iteration. You are modifying an existing Chrome extension. Below are the files in the current version (Version ${parentVerNum}):`;
      
      parentVer.files.forEach(f => {
        systemContext += `\n\n--- File Name: ${f.name} ---\n${f.content}`;
      });

      promptContent = `The user wants to iterate on the extension. 
Existing Prompt History: ${project.promptHistory ? project.promptHistory.join(' -> ') : ''}
New requirement to apply: "${prompt}"

Modify the existing files or create new ones to achieve this request. Provide the FULL revised project files matching the original JSON format, updating the 'manifest.json' version number if necessary. Maintain existing features unless the user's new request explicitly overrides them.`;
    }
  }

  try {
    let rawText = '';
    try {
      if (aiProvider === 'gemini') {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            system_instruction: { parts: [{ text: systemContext }] },
            contents: [{ parts: [{ text: promptContent }] }],
            generationConfig: { response_mime_type: 'application/json', temperature: 0.7 }
          })
        });
        if (!response.ok) {
          const errBody = await response.text();
          console.error('Gemini error body:', errBody);
          throw new Error(`Gemini API Error ${response.status}`);
        }
        const result = await response.json();
        rawText = result.candidates?.[0]?.content?.parts?.[0]?.text;
      } else if (aiProvider === 'anthropic') {
        const response = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01'
          },
          body: JSON.stringify({
            model: 'claude-3-5-sonnet-20240620',
            max_tokens: 4096,
            system: systemContext,
            messages: [{ role: 'user', content: promptContent }]
          })
        });
        if (!response.ok) {
          const errBody = await response.text();
          console.error('Anthropic error body:', errBody);
          throw new Error(`Anthropic API Error ${response.status}`);
        }
        const result = await response.json();
        rawText = result.content?.[0]?.text;
      } else {
        // Default to OpenAI
        const response = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`
          },
          body: JSON.stringify({
            model: 'gpt-4o-mini',
            messages: [
              { role: 'system', content: systemContext },
              { role: 'user', content: promptContent }
            ],
            response_format: { type: 'json_object' },
            temperature: 0.7
          })
        });
        if (!response.ok) {
          const errBody = await response.text();
          console.error('OpenAI error body:', errBody);
          throw new Error(`OpenAI API Error ${response.status}`);
        }
        const result = await response.json();
        rawText = result.choices?.[0]?.message?.content;
      }
    } catch (apiErr) {
      console.error('API call failed:', apiErr.message);
      throw apiErr;
    }
    
    if (!rawText) {
      throw new Error('API returned an empty response and mock fallback failed.');
    }

    const cleanedText = cleanJSONResponse(rawText);
    const extensionData = JSON.parse(cleanedText);

    if (!extensionData.files || !Array.isArray(extensionData.files)) {
      throw new Error('LLM output does not contain files array.');
    }

    // Verify manifest.json exists
    const hasManifest = extensionData.files.some(f => f.name.toLowerCase() === 'manifest.json');
    if (!hasManifest) {
      throw new Error('LLM did not generate a manifest.json file.');
    }

    // Create project / version structure
    const newVersion = {
      version: targetVersion,
      prompt: prompt,
      createdAt: new Date().toISOString(),
      files: extensionData.files
    };

    // Temporarily write and validate on physical disk before saving to DB
    const validatedProjectObj = project || { id: crypto.randomUUID() };
    writeToTempAndValidate(validatedProjectObj, newVersion);

    if (project) {
      project.versions.push(newVersion);
      project.promptHistory = project.promptHistory || [];
      project.promptHistory.push(prompt);
      project.name = extensionData.name || project.name;
      project.description = extensionData.description || project.description;
      project.updatedAt = new Date().toISOString();
    } else {
      project = {
        id: validatedProjectObj.id,
        name: extensionData.name || 'Unnamed Extension',
        description: extensionData.description || 'Custom generated Chrome extension.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        promptHistory: [prompt],
        versions: [newVersion]
      };
      db.push(project);
    }

    writeDB(db);
    res.json(project);

  } catch (err) {
    console.error('Generation Error:', err);
    res.status(500).json({ error: err.message || 'Failed to generate extension.' });
  }
});

// Endpoint to save manual user code modifications to db
app.post('/api/projects/:projectId/versions/:version/files', (req, res) => {
  const { projectId, version } = req.params;
  const { name, content } = req.body;

  if (!name || content === undefined) {
    return res.status(400).json({ error: 'File name and content are required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  const file = ver.files.find(f => f.name === name);
  if (!file) {
    ver.files.push({ name, content });
  } else {
    file.content = content;
  }

  try {
    // Re-verify local integrity
    writeToTempAndValidate(project, ver);
    project.updatedAt = new Date().toISOString();
    writeDB(db);
    res.json(project);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to download zip compiled physically on-the-fly from temp directory
app.get('/api/download/:projectId/:version', (req, res) => {
  const { projectId, version } = req.params;
  const db = readDB();
  const project = db.find(p => p.id === projectId);
  
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  try {
    // 1. Physically write files to temp folder and validate structure
    const tempDir = writeToTempAndValidate(project, ver);

    // 2. Set up ZIP streaming
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${project.name.replace(/[^a-zA-Z0-9]/g, '_')}_v${version}.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });
    
    archive.on('error', (err) => {
      console.error('Archive error:', err);
      res.status(500).send({ error: err.message });
    });

    archive.pipe(res);

    // 3. Zip files from the physical temp directory
    archive.directory(tempDir, false);
    archive.finalize();

  } catch (err) {
    console.error('Download Error:', err);
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to delete a project and clean up its files
app.delete('/api/projects/:projectId', (req, res) => {
  const { projectId } = req.params;
  const db = readDB();
  const projectIndex = db.findIndex(p => p.id === projectId);
  if (projectIndex === -1) {
    return res.status(404).json({ error: 'Project not found' });
  }
  
  // Remove from db
  db.splice(projectIndex, 1);
  writeDB(db);

  // Remove physical files
  const projectTempDir = path.join(TEMP_BASE_DIR, projectId);
  if (fs.existsSync(projectTempDir)) {
    try {
      fs.rmSync(projectTempDir, { recursive: true, force: true });
    } catch (err) {
      console.error('Error deleting temp directory:', err);
    }
  }
  
  res.json({ success: true });
});

// Endpoint to delete a file from a project version
app.post('/api/projects/:projectId/versions/:version/files/delete', (req, res) => {
  const { projectId, version } = req.params;
  const { name } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'File name is required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) {
    return res.status(404).json({ error: 'Version not found' });
  }

  const fileIndex = ver.files.findIndex(f => f.name === name);
  if (fileIndex === -1) {
    return res.status(404).json({ error: 'File not found' });
  }

  if (name.toLowerCase() === 'manifest.json') {
    return res.status(400).json({ error: 'Cannot delete manifest.json' });
  }

  ver.files.splice(fileIndex, 1);

  try {
    writeToTempAndValidate(project, ver);
    project.updatedAt = new Date().toISOString();
    writeDB(db);
    res.json(project);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Endpoint to update project metadata (rename / update description)
app.post('/api/projects/:projectId/metadata', (req, res) => {
  const { projectId } = req.params;
  const { name, description } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'Project name is required' });
  }

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) {
    return res.status(404).json({ error: 'Project not found' });
  }

  project.name = name;
  if (description !== undefined) {
    project.description = description;
  }
  project.updatedAt = new Date().toISOString();

  writeDB(db);
  res.json(project);
});

// ========== WEEK 4: CODE SANITIZATION ENGINE ==========
const DANGEROUS_PATTERNS = [
  { pattern: /eval\s*\(/gi, severity: 'critical', label: 'eval() usage detected — potential arbitrary code execution' },
  { pattern: /new\s+Function\s*\(/gi, severity: 'critical', label: 'new Function() constructor — potential arbitrary code execution' },
  { pattern: /document\.write\s*\(/gi, severity: 'warning', label: 'document.write() usage — potential XSS vector' },
  { pattern: /innerHTML\s*=/gi, severity: 'warning', label: 'innerHTML assignment — potential XSS vector' },
  { pattern: /outerHTML\s*=/gi, severity: 'warning', label: 'outerHTML assignment — potential XSS vector' },
  { pattern: /XMLHttpRequest|fetch\s*\(\s*['"`]https?:\/\/(?!api\.openai\.com|generativelanguage\.googleapis\.com)/gi, severity: 'warning', label: 'External network request detected — verify destination URL' },
  { pattern: /chrome\.cookies/gi, severity: 'critical', label: 'chrome.cookies API access — sensitive data exposure risk' },
  { pattern: /chrome\.history/gi, severity: 'warning', label: 'chrome.history API access — privacy-sensitive data' },
  { pattern: /chrome\.bookmarks/gi, severity: 'info', label: 'chrome.bookmarks API access — user data' },
  { pattern: /chrome\.tabs\.executeScript/gi, severity: 'critical', label: 'Dynamic script injection via chrome.tabs — code execution risk' },
  { pattern: /chrome\.debugger/gi, severity: 'critical', label: 'chrome.debugger API — highly privileged access' },
  { pattern: /crypto\s*\.\s*subtle/gi, severity: 'info', label: 'Web Crypto API usage — review cryptographic operations' },
  { pattern: /CryptoMiner|coinhive|coin-hive|minero/gi, severity: 'critical', label: 'Potential cryptocurrency mining code detected' },
  { pattern: /keydown|keyup|keypress/gi, severity: 'warning', label: 'Keyboard event listener — potential keylogging' },
  { pattern: /password|passwd|creditcard|credit_card|ssn/gi, severity: 'warning', label: 'References to sensitive data fields detected' },
  { pattern: /atob\s*\(|btoa\s*\(/gi, severity: 'info', label: 'Base64 encoding/decoding — review for obfuscated payloads' },
  { pattern: /window\.open\s*\(/gi, severity: 'info', label: 'window.open() usage — potential popup/redirect' },
  { pattern: /<script[^>]*src\s*=\s*['"]https?:\/\//gi, severity: 'critical', label: 'External script loading in HTML — potential supply chain risk' },
];

const scanCodeForThreats = (files) => {
  const findings = [];
  let criticalCount = 0;
  let warningCount = 0;
  let infoCount = 0;

  files.forEach(file => {
    if (!file.content || file.name.toLowerCase() === 'manifest.json') return;
    
    DANGEROUS_PATTERNS.forEach(({ pattern, severity, label }) => {
      // Reset regex state
      pattern.lastIndex = 0;
      const matches = file.content.match(pattern);
      if (matches) {
        findings.push({
          file: file.name,
          severity,
          label,
          occurrences: matches.length
        });
        if (severity === 'critical') criticalCount += matches.length;
        else if (severity === 'warning') warningCount += matches.length;
        else infoCount += matches.length;
      }
    });
  });

  const score = Math.max(0, 100 - (criticalCount * 25) - (warningCount * 10) - (infoCount * 2));
  const grade = score >= 90 ? 'A' : score >= 75 ? 'B' : score >= 50 ? 'C' : score >= 25 ? 'D' : 'F';

  return {
    score,
    grade,
    findings,
    summary: {
      critical: criticalCount,
      warning: warningCount,
      info: infoCount,
      totalFiles: files.length,
      scannedAt: new Date().toISOString()
    }
  };
};

// Endpoint: Run security scan on a project version
app.post('/api/projects/:projectId/versions/:version/security-scan', (req, res) => {
  const { projectId, version } = req.params;
  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) return res.status(404).json({ error: 'Project not found' });

  const verNum = parseInt(version);
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) return res.status(404).json({ error: 'Version not found' });

  const scanResult = scanCodeForThreats(ver.files);
  res.json(scanResult);
});

// ========== WEEK 3: EDIT REQUEST ENDPOINT (AI-powered iterative modification) ==========
const EDIT_SYSTEM_INSTRUCTION = `You are a world-class AI Chrome Extension Developer expert. 
You are being asked to MODIFY an existing Chrome Extension based on the user's edit request.

CRITICAL RULES:
1. You MUST preserve ALL existing functionality unless the user explicitly asks to remove it.
2. Apply ONLY the requested changes — do not refactor, rename, or restructure anything unnecessarily.
3. You MUST use Manifest V3.
4. Every file referenced in manifest.json must exist in the files list.
5. Return the COMPLETE set of files (both modified and unmodified) in your response.
6. If the change only affects one file, still return all other files unchanged.

OUTPUT FORMAT:
You MUST output ONLY a valid JSON object. Do NOT wrap in markdown code blocks.

{
  "name": "Extension name (keep existing unless rename requested)",
  "description": "Extension description (update if behavior changed)",
  "files": [
    {
      "name": "manifest.json",
      "content": "{ ... }"
    },
    ...all other files...
  ]
}`;

app.post('/api/edit', async (req, res) => {
  const { projectId, version, editPrompt, apiKey: frontendApiKey } = req.body;
  const apiKey = frontendApiKey || process.env.OPENAI_API_KEY;

  if (!editPrompt) return res.status(400).json({ error: 'Edit prompt is required' });
  if (!projectId) return res.status(400).json({ error: 'Project ID is required' });
  if (!apiKey) return res.status(400).json({ error: 'API Key is required' });

  const db = readDB();
  const project = db.find(p => p.id === projectId);
  if (!project) return res.status(404).json({ error: 'Project not found' });

  const verNum = parseInt(version) || project.versions[project.versions.length - 1].version;
  const ver = project.versions.find(v => v.version === verNum);
  if (!ver) return res.status(404).json({ error: 'Version not found' });

  // Build context with current files
  let fileContext = `Below are ALL the current files in this Chrome Extension (Version ${verNum}):\n`;
  ver.files.forEach(f => {
    fileContext += `\n--- File: ${f.name} ---\n${f.content}\n`;
  });

  const userPrompt = `${fileContext}\n\nEDIT REQUEST: "${editPrompt}"\n\nApply this edit to the extension. Return the full updated file set.`;

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: EDIT_SYSTEM_INSTRUCTION },
          { role: 'user', content: userPrompt }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.7
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenAI API error ${response.status}: ${errorText}`);
    }

    const result = await response.json();
    const rawText = result.choices?.[0]?.message?.content;
    if (!rawText) throw new Error('OpenAI returned empty response');

    const cleanedText = cleanJSONResponse(rawText);
    const extensionData = JSON.parse(cleanedText);

    if (!extensionData.files || !Array.isArray(extensionData.files)) {
      throw new Error('LLM output missing files array');
    }

    // Create new version from edit
    const newVersion = {
      version: project.versions.length + 1,
      prompt: `[Edit] ${editPrompt}`,
      createdAt: new Date().toISOString(),
      files: extensionData.files
    };

    // Validate before saving
    writeToTempAndValidate(project, newVersion);

    // Run security scan on new code
    const securityScan = scanCodeForThreats(extensionData.files);

    project.versions.push(newVersion);
    project.promptHistory = project.promptHistory || [];
    project.promptHistory.push(`[Edit] ${editPrompt}`);
    project.name = extensionData.name || project.name;
    project.description = extensionData.description || project.description;
    project.updatedAt = new Date().toISOString();

    writeDB(db);
    res.json({ project, securityScan });

  } catch (err) {
    console.error('Edit Error:', err);
    res.status(500).json({ error: err.message || 'Failed to apply edit' });
  }
});

// Start backend
app.listen(PORT, () => {
  console.log(`Backend server is running on http://localhost:${PORT}`);
});
